INSERT INTO public.exercises (name, category, is_supplemental) VALUES
  ('Bench Press', 'Push', false),
  ('Overhead Press', 'Push', false),
  ('Plyo Push-Up', 'Push', false),
  ('Barbell Row', 'Pull', false),
  ('Weighted Pull-Up', 'Pull', false),
  ('Pull-Up', 'Pull', false),
  ('Trap Bar Deadlift', 'Legs', false),
  ('Zercher Squat', 'Legs', false),
  ('Speed Squat', 'Legs', false),
  ('Box Jump', 'Legs', false),
  ('KB Swing', 'Legs', false),
  ('Gi Pull-Ups', 'Grip', true),
  ('Plate Pinch Hold', 'Grip', true),
  ('Towel Hang', 'Grip', true),
  ('Neck Rotations', 'Neck', true),
  ('Supine Neck Flexion', 'Neck', true),
  ('Pallof Press', 'Push', true),
  ('Sandbag Get-Up', 'Legs', true),
  ('Zone 2 Steady State', 'Cardio', false),
  ('Aerodyne Intervals', 'Cardio', false),
  ('Alactic Sprints', 'Cardio', false);
